### ISSUE TITLE
Feedback reproductive workshop

### ISSUE THREAD

**Issue by KellyWYChin** [linda169/Time-series-R#1]
REPRODUCING CODE: WHAT DID YOU LEARN?

Go to the GitHub repository of the project you're reproducing -> Open an 'Issue' -> Copy all the text below the --- into that 'Issue' -> Start answering the questions there.

Hint: you can place an X within the square brackets to mark off a checkbox, like this: [X] Yes

---

**1. What project did you reproduce (include the link)?**

-> IndAss_Ilic_Linda.Rmd

**2. Does the project have the following on it's GitHub repository?**

- [X] README
- [X] A license
- [ ] Citation information
- [X] Requirements for running the code (dependencies)
- [X] An understandable folder structure

**3. What did you appreciate about the project's repository?**

-> Very clean with only a few folders which makes it easy to find the file

**4. Do you have any suggestions for improvement to the repository?**

-> Including a project in the repository will be much easier for others to open the project and run on their own computers

**5. Did you manage to run the project successfully?**

- [ ] Yes
- [ ] Largely
- [X] No
- [ ] Other (please specify):

**6. Where did you have to give up reproducing this repository (if applicable)?**

-> Cannot open the file ESMdata.csv. Maybe there is no such dataset in the repository.

**7. Did you have to go into the code?**

- [ ] Yes
- [X] No
- [ ] I didn't have to, but I had time left/was intrigued, so I did it anyway!

**8. If you looked at the code: what did you like?**

-> Very tidy, clean, easy to understand

**9. If you looked at the code, what would be a single line of advice you want to pass on to it's author?**

-> very well done project!

**10. Any final comments to the author?**

-> Remarkable! Create a project link to the repository and upload the file.

**11. Do you think the class will benefit from a live demo of the reproduction of this project? Why/what can we learn?**

-> I think either online or on-site is fine!

**Comment by linda169** [comment]
Thanks for the feedback, Kelly!

**Comment by linda169** [comment]
> REPRODUCING CODE: WHAT DID YOU LEARN?
> 
> Go to the GitHub repository of the project you're reproducing -> Open an 'Issue' -> Copy all the text below the --- into that 'Issue' -> Start answering the questions there.
> 
> Hint: you can place an X within the square brackets to mark off a checkbox, like this: [X] Yes
> 
> **1. What project did you reproduce (include the link)?**
> 
> -> IndAss_Ilic_Linda.Rmd
> 
> **2. Does the project have the following on it's GitHub repository?**
> 
>     * [x]  README
> 
>     * [x]  A license
> 
>     * [ ]  Citation information
> 
>     * [x]  Requirements for running the code (dependencies)
> 
>     * [x]  An understandable folder structure
> 
> 
> **3. What did you appreciate about the project's repository?**
> 
> -> Very clean with only a few folders which makes it easy to find the file
> 
> **4. Do you have any suggestions for improvement to the repository?**
> 
> -> Including a project in the repository will be much easier for others to open the project and run on their own computers
> 
> **5. Did you manage to run the project successfully?**
> 
>     * [ ]  Yes
> 
>     * [ ]  Largely
> 
>     * [x]  No
> 
>     * [ ]  Other (please specify):
> 
> 
> **6. Where did you have to give up reproducing this repository (if applicable)?**
> 
> -> Cannot open the file ESMdata.csv. Maybe there is no such dataset in the repository.
> 
> **7. Did you have to go into the code?**
> 
>     * [ ]  Yes
> 
>     * [x]  No
> 
>     * [ ]  I didn't have to, but I had time left/was intrigued, so I did it anyway!
> 
> 
> **8. If you looked at the code: what did you like?**
> 
> -> Very tidy, clean, easy to understand
> 
> **9. If you looked at the code, what would be a single line of advice you want to pass on to it's author?**
> 
> -> very well done project!
> 
> **10. Any final comments to the author?**
> 
> -> Remarkable! Create a project link to the repository and upload the file.
> 
> **11. Do you think the class will benefit from a live demo of the reproduction of this project? Why/what can we learn?**
> 
> -> I think either online or on-site is fine!
